<?php

namespace App\Services\Export;

/**
 * Text written into the account export. A file has no client to resolve i18n
 * keys, so — like the e-mails — labels and coded values are translated
 * server-side from the user's locale, in the app's own wording (same terms as
 * the frontend locales).
 */
final class AccountExportLabels
{
    private const LABELS = [
        'fr' => [
            'sheets' => ['account' => 'Compte', 'trades' => 'Trades', 'orders' => 'Ordres non exécutés'],
            'field' => 'Champ',
            'value' => 'Valeur',
            'yes' => 'Oui',
            'no' => 'Non',
            'account' => [
                'name' => 'Nom',
                'account_type' => 'Type',
                'stage' => 'Phase',
                'broker' => 'Broker',
                'currency' => 'Devise',
                'initial_capital' => 'Capital initial',
                'current_capital' => 'Solde',
                'max_drawdown' => 'Drawdown max',
                'daily_drawdown' => 'Drawdown journalier',
                'profit_target' => 'Objectif de profit',
                'profit_split' => 'Partage des profits (%)',
                'exported_at' => 'Exporté le',
            ],
            'adjustments' => ['adjusted_at' => 'Ajustement de solde', 'amount' => 'Montant', 'reason' => 'Motif'],
            'columns' => [
                'trade_number' => 'N° trade',
                'order_number' => 'N° ordre',
                'status' => 'Statut',
                'order_created_at' => 'Ordre placé le',
                'placed_at' => 'Placé le',
                'expires_at' => 'Expiration',
                'opened_at' => 'Ouverture',
                'secured_at' => 'Sécurisé le',
                'closed_at' => 'Clôture',
                'symbol' => 'Symbole',
                'direction' => 'Sens',
                'size' => 'Taille',
                'remaining_size' => 'Taille restante',
                'entry_price' => "Prix d'entrée",
                'sl_price' => 'SL (prix)',
                'be_price' => 'BE (prix)',
                'be_size' => 'BE (taille)',
                'target' => 'Objectif',
                'target_price' => 'Objectif (prix)',
                'target_size' => 'Objectif (taille)',
                'exit_at' => 'Sortie (date)',
                'exit_price' => 'Sortie (prix)',
                'exit_size' => 'Sortie (taille)',
                'exit_kind' => 'Sortie (type)',
                'exit_pnl' => 'Sortie (P&L)',
                'avg_exit_price' => 'Prix de sortie moyen',
                'exit_type' => 'Type de sortie',
                'risk_reward' => 'R:R',
                'pnl' => 'P&L du trade',
                'plan' => 'Plan',
                'plan_adherence' => 'Respect du plan',
                'plan_adherence_reason' => 'Raison',
                'setup_timeframe' => 'Setup : Timeframe',
                'setup_pattern' => 'Setup : Pattern',
                'setup_context' => 'Setup : Contexte',
                'setup_uncategorized' => 'Setup : non catégorisé',
                'custom_fields' => 'Champs personnalisés',
                'notes' => 'Notes',
            ],
            'values' => [
                'account_type' => ['BROKER_DEMO' => 'Démo', 'BROKER_LIVE' => 'Compte propre', 'PROP_FIRM' => 'Prop Firm'],
                'stage' => ['CHALLENGE' => 'Challenge', 'VERIFICATION' => 'Vérification', 'FUNDED' => 'Funded'],
                'direction' => ['BUY' => 'Achat', 'SELL' => 'Vente'],
                'trade_status' => ['OPEN' => 'Ouvert', 'SECURED' => 'Sécurisé', 'CLOSED' => 'Fermé'],
                'order_status' => ['PENDING' => 'En attente', 'EXECUTED' => 'Exécuté', 'CANCELLED' => 'Annulé', 'EXPIRED' => 'Expiré'],
                'exit_type' => ['TP' => 'Take Profit', 'SL' => 'Stop Loss', 'BE' => 'Breakeven', 'MANUAL' => 'Manuel'],
                'plan_adherence' => ['IN_PLAN' => 'Dans le plan', 'OUT_OF_PLAN' => 'Hors plan'],
            ],
        ],
        'en' => [
            'sheets' => ['account' => 'Account', 'trades' => 'Trades', 'orders' => 'Unexecuted orders'],
            'field' => 'Field',
            'value' => 'Value',
            'yes' => 'Yes',
            'no' => 'No',
            'account' => [
                'name' => 'Name',
                'account_type' => 'Type',
                'stage' => 'Stage',
                'broker' => 'Broker',
                'currency' => 'Currency',
                'initial_capital' => 'Initial capital',
                'current_capital' => 'Balance',
                'max_drawdown' => 'Max drawdown',
                'daily_drawdown' => 'Daily drawdown',
                'profit_target' => 'Profit target',
                'profit_split' => 'Profit split (%)',
                'exported_at' => 'Exported on',
            ],
            'adjustments' => ['adjusted_at' => 'Balance adjustment', 'amount' => 'Amount', 'reason' => 'Reason'],
            'columns' => [
                'trade_number' => 'Trade no.',
                'order_number' => 'Order no.',
                'status' => 'Status',
                'order_created_at' => 'Order placed on',
                'placed_at' => 'Placed on',
                'expires_at' => 'Expiry',
                'opened_at' => 'Opened',
                'secured_at' => 'Secured on',
                'closed_at' => 'Closed',
                'symbol' => 'Symbol',
                'direction' => 'Direction',
                'size' => 'Size',
                'remaining_size' => 'Remaining size',
                'entry_price' => 'Entry price',
                'sl_price' => 'SL (price)',
                'be_price' => 'BE (price)',
                'be_size' => 'BE (size)',
                'target' => 'Target',
                'target_price' => 'Target (price)',
                'target_size' => 'Target (size)',
                'exit_at' => 'Exit (date)',
                'exit_price' => 'Exit (price)',
                'exit_size' => 'Exit (size)',
                'exit_kind' => 'Exit (type)',
                'exit_pnl' => 'Exit (P&L)',
                'avg_exit_price' => 'Average exit price',
                'exit_type' => 'Exit type',
                'risk_reward' => 'R:R',
                'pnl' => 'Trade P&L',
                'plan' => 'Plan',
                'plan_adherence' => 'Plan adherence',
                'plan_adherence_reason' => 'Reason',
                'setup_timeframe' => 'Setup: Timeframe',
                'setup_pattern' => 'Setup: Pattern',
                'setup_context' => 'Setup: Context',
                'setup_uncategorized' => 'Setup: uncategorized',
                'custom_fields' => 'Custom fields',
                'notes' => 'Notes',
            ],
            'values' => [
                'account_type' => ['BROKER_DEMO' => 'Demo', 'BROKER_LIVE' => 'Personal', 'PROP_FIRM' => 'Prop Firm'],
                'stage' => ['CHALLENGE' => 'Challenge', 'VERIFICATION' => 'Verification', 'FUNDED' => 'Funded'],
                'direction' => ['BUY' => 'Buy', 'SELL' => 'Sell'],
                'trade_status' => ['OPEN' => 'Open', 'SECURED' => 'Secured', 'CLOSED' => 'Closed'],
                'order_status' => ['PENDING' => 'Pending', 'EXECUTED' => 'Executed', 'CANCELLED' => 'Cancelled', 'EXPIRED' => 'Expired'],
                'exit_type' => ['TP' => 'Take Profit', 'SL' => 'Stop Loss', 'BE' => 'Breakeven', 'MANUAL' => 'Manual'],
                'plan_adherence' => ['IN_PLAN' => 'In plan', 'OUT_OF_PLAN' => 'Out of plan'],
            ],
        ],
    ];

    private const FALLBACK = 'en';

    public static function for(?string $locale): array
    {
        return self::LABELS[$locale] ?? self::LABELS[self::FALLBACK];
    }
}
