upload_max_filesize = 32M
post_max_size = 32M
memory_limit = 256M
max_execution_time = 60

display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /dev/stderr

session.cookie_httponly = 1
session.cookie_secure = 1
session.cookie_samesite = Lax
